@startuml
title Vindkraftverk - Objekttyper

skinparam class {
  AttributeIconSize 0
}

package "Objekttyper" {

  class VindkraftverkOmr <<featureType>> {
    + område [1] : Flate
  }

  class Vindturbin <<featureType>> {
    + posisjon [1] : Punkt
  }

  class VindkraftverkPkt <<featureType>> {
    + posisjon [1] : Punkt
  }

  abstract class Vindkraft <<featureType>> {
    + anleggsNavn [0..1] : CharacterString
    + dataUttaksdato [0..1] : Date
    + eksportType [0..1] : CharacterString
    + identifikasjon [1] : Identifikasjon
    + sakKategori [0..1] : SaksKategori_NVE
  }

  abstract class Vindkraftverk <<featureType>> {
    + effekt_MW_idrift [0..1] : Real
    + effektMW [0..1] : Real
    + eier [0..1] : CharacterString
    + forventetProduksjonGWh [0..1] : Real
    + fylkesnavn [0..1] : CharacterString
    + idriftDato [0..1] : Date
    + kommunenavn [0..1] : CharacterString
    + sakID [0..1] : Integer
    + sakLenke [0..1] : CharacterString
    + status [0..1] : Status_GEN
    + totaltAntTurbiner [0..1] : Integer
    + utAvDriftDato [0..1] : Date
  }

  class Identifikasjon {
    + lokalId [1] : CharacterString
    + navnerom [1] : CharacterString
  }
}

  Vindkraftverk <|-- VindkraftverkOmr
  Vindkraft <|-- Vindturbin
  Vindkraftverk <|-- VindkraftverkPkt
  Vindkraft <|-- Vindkraftverk

@enduml
