metadataId: ac249604-cd82-490c-83cc-9cd24fe18088
ogc_feature_api: https://kos-pygeoapi.atkv3-dev.kartverket.cloud/collections
output_directory: produktspesifikasjon
product_slug: admenheter
updated: 2025-11-28
xmi_url: https://sosi.geonorge.no/svn/SOSI/SOSI Del 3/Norges vassdrags- og energidirektorat/Vindkraft-1.0.xml
